export const GET_ALL_MOVIE_REQUEST = "GET_ALL_MOVIE_REQUEST";
export const GET_ALL_MOVIE_SUCCESS = "GET_ALL_MOVIE_SUCCESS";
export const GET_ALL_MOVIE_FAILURE = "GET_ALL_MOVIE_FAILURE";


export const GET_ALL_MOVIEDETAILS_REQUEST = "GET_ALL_MOVIEDETAILS_REQUEST";
export const GET_ALL_MOVIEDETAILS_SUCCESS = "GET_ALL_MOVIEDETAILS_SUCCESS";
export const GET_ALL_MOVIEDETAILS_FAILURE = "GET_ALL_MOVIEDETAILS_FAILURE";

export const GET_ALL_MOVIE_SEARCH_REQUEST = "GET_ALL_MOVIE_SEARCH_REQUEST";
export const GET_ALL_MOVIE_SEARCH_SUCCESS = "GET_ALL_MOVIE_SEARCH_SUCCESS";
export const GET_ALL_MOVIE_SEARCH_FAILURE = "GET_ALL_MOVIE_SEARCH_FAILURE";